### ISSUE TITLE
Differentiate imports from import keyword in Java.

### ISSUE THREAD

**Issue by arnavb** [juliettepretot/lucy-vscode-theme#5]
I was using this theme for Java, but I noticed this:

![screen shot 2019-01-30 at 6 41 11 am](https://user-images.githubusercontent.com/30810402/51979042-0f11eb80-245a-11e9-9221-b7e95002d22a.png)

As you can see, the names being imported are the same color as the `import` keyword. Would you consider changing this theme so that there is some sort of color difference there?

**Comment by flrnd** [comment]
Hey there @arnavb. You can fix it very easy adding this in getTheme.mjs: 
```css
{
  scope: ["storage.modifier.package", "storage.modifier.import"],
    settings: {
      foreground: colors.const
    }
},
```
Then run `npm run build` and this is it. Also you can choose any color from colors.mjs and you are set.
Hope it helps! Cheers.
